### ISSUE TITLE
Does this template work on macos? 

### ISSUE THREAD

**Issue by conanchen** [yooneskh/vite-tauri-template#1]
I tested this template on macos, 
I got corrent screen of http://localhost:8080/ after I ran "yarn serve:native", 

but could not got the correct screen of bundle/macos/vite-tauri-template.app after i ran "yarn build"

![image](https://user-images.githubusercontent.com/1233799/130420611-4727599a-2511-44bb-b505-739c174ccfa5.png)

**Comment by yooneskh** [comment]
Hello @conanchen sorry for late reply. This is probably fixed by the latest updates to Tauri and changes made to build stage. I will try to apply the updates and check this issue.

**Comment by yooneskh** [comment]
I reinstalled my `rustup` and re added `tauri` to the `vite` project and it builds just fine now.

this is my `tauri info` output.

```
Operating System - Fedora, version 34.0.0 X64

Node.js environment
  Node.js - 16.8.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.21.0
  yarn - 1.22.11

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/public
/src
/dist
/.git
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:8080
  framework - Vue.js
```
