### ISSUE TITLE
VITE_HTTP_HANDLER is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Congb19** [yooneskh/vite-tauri-template#3]
When I run serve:native script (VITE_HTTP_HANDLER=NATIVE vite --port 8080), 
console: ` VITE_HTTP_HANDLER is not recognized as an internal or external command`

what can i do with it?

**Comment by yooneskh** [comment]
Are you on windows?

**Comment by Congb19** [comment]
> Are you on windows?

Yes! I will try macos later!
but what should i do on windows that can solve the problem?

**Comment by yooneskh** [comment]
on windows you must replace the script with this

set VITE_HTTP_HANDLER=NATIVE && vite --port 8080
