### ISSUE TITLE
The compiled package does not work properly

### ISSUE THREAD

**Issue by itinybad** [yooneskh/vite-tauri-template#4]
When I cloned the git repository and executed `yarn run serve` and `yarn run serve:tauri`, it executed as expected, but the packages compiled by executing `yarn run build:web` and `yarn run build` did not work properly under windows.
![image](https://user-images.githubusercontent.com/13375605/169690175-16c30d8f-84fb-4c6d-94ce-41a1eabe6619.png)
The software will automatically close after the white screen

**Comment by yooneskh** [comment]
Tauri is currently in the process of releasing version 1, and is releasing the RC versions. I will recheck the entire repo after v1 is released and fix this if it is still in the v1.

**Comment by yooneskh** [comment]
This template is remade with Tauri 1 and Vite 3. Please reclone it again and see if it is fixed. If not, please open this issue again.
