### ISSUE TITLE
After fresh cloning and running serve:tauri Could not connect: Connection refused

### ISSUE THREAD

**Issue by skopz356** [yooneskh/vite-tauri-template#6]
After fresh cloning the repo and installing tauri and npm dependencies. When I run serve:tauri the window is blank with error "Could not connect: Connection refused". 
![Screenshot from 2022-06-18 11-53-47](https://user-images.githubusercontent.com/36794259/174432661-fe51a611-1a15-4b4c-8392-37d31d8871dc.png)

**Comment by yooneskh** [comment]
Hello. I am planning to upgrade the project to tauri v1 soon. This will be fixed with it too.

**Comment by ismaail** [comment]
to work, I changed tauri versions in package.json

```json
"@tauri-apps/api": "1.0.2",
"@tauri-apps/cli": "1.0.4",
```

then run `npm run build`,

I'm on Linux so I tried with AppImage.

![image](https://user-images.githubusercontent.com/4411670/179430231-c6334810-6a93-4459-8a95-ec0526a6822e.png)

The API request didn't work though and the command `npm run serve:tauri` fails with warnings:
```
Warn Waiting for your frontend dev server to start on http://localhost:8080/...
Warn Waiting for your frontend dev server to start on http://localhost:8080/...
```

**Comment by yooneskh** [comment]
This template is remade with Tauri 1 and Vite 3. Please reclone it again and see if it is fixed. If not, please open this issue again.

**Comment by ismaail** [comment]
@yooneskh it works, thanks.
