### ISSUE TITLE
Can't start App

### ISSUE THREAD

**Issue by vanminhquangtri** [yooneskh/vite-tauri-template#9]
hello, thanks for your nice project. 
after yarn install, I can't start the app, both command serve:tauri & serve:native.
my OS is Window 11 Pro 64 bit, Node version 18.16.0. Yarn version 1.22.19

the error of **serve:tauri is:**
**'VITE_NETWORK_PROCESSOR' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

while error of **serve:native**
**thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', src\interface\rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Done in 1.14s.**

Do I need to add any config or env?

![image](https://github.com/yooneskh/vite-tauri-template/assets/70369658/ac8aa96e-6425-496d-83d2-987784518dd3)

**Comment by vanminhquangtri** [comment]
I was able to fixed by install all Prerequisites as mentioned at: https://tauri.app/v1/guides/getting-started/prerequisites.
Thanks

**Comment by yooneskh** [comment]
Another problem you faced was setting en env var in windows. I updated the repo to use `cross-env` so windows users will b able to set env vars too.

All of the dependencies are updated too. You should repull from this repo if you can.
